name: Automatic PR Content Generator

on:
  workflow_dispatch:
    inputs:
      runWorkflow:
        description: 'Manually trigger this workflow?'
        required: true
        default: 'yes'
  pull_request:
    types: [opened, reopened,synchronize]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  prepare_and_generate_content:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get diff of the pull request
        id: get_diff
        shell: bash
        run: |
          git fetch origin "${{ github.event.pull_request.head.ref }}"
          git fetch origin "${{ github.event.pull_request.base.ref }}"
          git diff "origin/${{ github.event.pull_request.base.ref }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT

      - name: Update PR with generated content
        uses: rubensflinco/gemini-code-review-action@1.0.5
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: gemini-1.5-pro-latest
          extra_prompt: "Provide a concise summary of the pull request changes."
          temperature: 0.7
          max_tokens: 256
          pull_request_diff: ${{ steps.get_diff.outputs.pull_request_diff }}
