name: Automatic PR Content Generator

on:
  pull_request:
    types: [opened, reopened, synchronized]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  prepare_and_generate_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get diff of the pull request
        id: get_diff
        shell: bash
        run: |
          git fetch origin "${{ github.event.pull_request.head.ref }}"
          git fetch origin "${{ github.event.pull_request.base.ref }}"

          git checkout "${{ github.event.pull_request.head.ref }}"
          git diff "origin/${{ github.event.pull_request.base.ref }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT

      - name: Generate PR content
        id: generate_content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          API_PROVIDER: "gemini"
        run: python .github/scripts/generate_pr_content.py

      - name: Update PR with generated content
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pull request content
          title: 'Automatically Generated PR Summary'
          body: ${{ steps.generate_content.outputs.pr_content }}
          branch: 'auto-pr-content-branch'
