name: Automatic PR Content Generator

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:  # Manual trigger
    inputs:
      base_ref:
        description: "Base branch for manual trigger (default: main)"
        required: false
        default: "main"
      head_ref:
        description: "Head branch for manual trigger (default: feature)"
        required: false
        default: "feature"

jobs:
  prepare_and_generate_content:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get diff of the pull request
        id: get_diff
        shell: bash
        run: |
          # Determine base and head refs
          BASE_REF="${{ github.event.pull_request.base.ref || github.event.inputs.base_ref }}"
          HEAD_REF="${{ github.event.pull_request.head.ref || github.event.inputs.head_ref }}"
          
          # Fetch branches and generate diff
          git fetch origin "$HEAD_REF" || echo "Failed to fetch head branch $HEAD_REF"
          git fetch origin "$BASE_REF" || echo "Failed to fetch base branch $BASE_REF"
          git diff "origin/$BASE_REF" > "diff.txt" || echo "Git diff failed"

          # Validate diff file content
          if [ ! -s diff.txt ]; then
            echo "No changes detected or invalid diff file. Exiting gracefully."
            exit 0
          fi

          # Save diff output to GitHub Actions output
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT

      - name: Generate PR content
        if: ${{ steps.get_diff.outputs.pull_request_diff != '' }}
        run: |
          python generate_pr_content.py
        env:
          API_PROVIDER: ${{ secrets.API_PROVIDER }}  # Set to "openai" or "gemini"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # If using OpenAI
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # If using Gemini
